# MiyooPorts makefile

# MiyooPorts platform identifier
PLATFORM = miyooports

include Makefile.common

# MiyooPorts-specific settings
LIBS = $(COMMON_LIBS) platforms/sdl12
OUTPUT_EXT =
DOCKER32 = docker run --privileged --platform=linux/armhf --rm --user $$(id -u):$$(id -g) -v`pwd`/..:/src -w/src/tracker

# MiyooPorts build settings
XTRA_CFLAGS = -DMIYOOPORTS_BUILD -I${SYSROOT}/usr/include -L${SYSROOT}/usr/lib
XTRA_LIBS = -lSDL -lm
JOBS ?= 4
CFLAGS = $(filter-out -flto,$(COMMON_CFLAGS)) $(INCLUDES) $(XTRA_CFLAGS)
object_for = $(BUILD)/obj/$(subst ../,up/,$(basename $(1))).o
OBJECTS := $(foreach source,$(SOURCES),$(call object_for,$(source)))
DEPS := $(OBJECTS:.o=.d)

define compile_source
$(call object_for,$(1)): $(1) Makefile.miyooports Makefile.common
	@mkdir -p $$(dir $$@)
	@$(CROSS_COMPILE)$(CC) $(CFLAGS) -MMD -MP -c $$< -o $$@
endef

$(foreach source,$(SOURCES),$(eval $(call compile_source,$(source))))
-include $(DEPS)

.PHONY: .MiyooPorts
.MiyooPorts: $(BUILD)/chipnomad.armhf

$(BUILD)/chipnomad.armhf: $(OBJECTS)
	mkdir -p $(BUILD)
	$(CROSS_COMPILE)$(CC) $(CFLAGS) $(OBJECTS) $(XTRA_LIBS) -o $@
	chmod +x $@

.PHONY: MiyooPorts
MiyooPorts:
	@./check-docker.sh || exit 1
	$(DOCKER32) monkeyx/retro_builder:arm32 make -j$(JOBS) -f Makefile.miyooports .MiyooPorts CC=g++ CPU=armhf JOBS=$(JOBS)

.PHONY: MiyooPorts-deploy
MiyooPorts-deploy: MiyooPorts
	@echo "Creating MiyooPorts deployment package..."
	@mkdir -p ../../releases
	@rm -rf /tmp/chipnomad-miyooports-package
	@mkdir -p /tmp/chipnomad-miyooports-package/Roms/PORTS/Games/ChipNomad
	@mkdir -p /tmp/chipnomad-miyooports-package/Roms/PORTS/Imgs
	@mkdir -p /tmp/chipnomad-miyooports-package/Roms/PORTS/Shortcuts/ChipNomad
	@cp $(BUILD)/chipnomad.armhf /tmp/chipnomad-miyooports-package/Roms/PORTS/Games/ChipNomad/
	@cp -r packaging/common/* /tmp/chipnomad-miyooports-package/Roms/PORTS/Games/ChipNomad/
	@cp packaging/chipnomad-icon.png /tmp/chipnomad-miyooports-package/Roms/PORTS/Imgs/ChipNomad.png
	@cp -r packaging/miyoo_ports/* /tmp/chipnomad-miyooports-package/Roms/PORTS/Shortcuts/ChipNomad
	@cd /tmp/chipnomad-miyooports-package && zip -r ChipNomad-$$(date +%Y-%m-%d)-$(VERSION)-MiyooPorts.zip .
	@mv /tmp/chipnomad-miyooports-package/ChipNomad-*-MiyooPorts.zip ../../releases/
	@rm -rf /tmp/chipnomad-miyooports-package
	@echo "MiyooPorts package created in ../../releases/"
